import { Product } from "@/lib/types"


export const defaultProducts: Product[] = [
  {
    uuid: "1",
    name: "Rubber Ball with Spikes",
    description:
      "Durable rubber ball with spikes for interactive play. Black with vibrant green accents for visibility.",
    price: 12.99,
    stock: 1,
    category: "toy",
    imageUrl: "/placeholder-t1old.png",
    sku: 'H123THP',
  },
  {
    uuid: "2",
    name: "Plush Monkey Toy",
    description: "Soft and cuddly plush monkey toy. Brown with orange accents, perfect for comfort and play.",
    price: 15.99,
    stock: 1,
    category: "toy",
    imageUrl: "/brown-orange-plush-monkey.png",
    sku: 'HFPP12HAP',
  },
  {
    uuid: "3",
    name: "Collapsible Pet Bowl",
    description: "Convenient collapsible bowl for travel and outdoor adventures. Blue and green design.",
    price: 8.99,
    stock: 2,
    category: "accessory",
    imageUrl: "/placeholder-q8gyj.png",
    sku: 'H123THPF',
  },
  {
    uuid: "4",
    name: "Metal Carabiners",
    description: "Heavy-duty metal carabiners for secure leash attachment. Blue and green finish.",
    price: 6.99,
    stock: 2,
    category: "accessory",
    imageUrl: "/placeholder-05r2x.png",
    sku: 'H123THPA',
  },
  {
    uuid: "5",
    name: "Training Clicker",
    description: "Professional training clicker for positive reinforcement. Durable black construction.",
    price: 4.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/placeholder-irykk.png",
    sku: 'H123THPS',
  },
  {
    uuid: "6",
    name: "Doorbell Strap",
    description: "Training doorbell strap with silver bells. Black strap for door handle attachment.",
    price: 9.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/placeholder-1dj9c.png",
    sku: 'H123THPT',
  },
  {
    uuid: "7",
    name: "Knotted Rope Toy",
    description: "Natural rope toy with knots for chewing and tugging. Blue and white cotton rope.",
    price: 11.99,
    stock: 1,
    category: "toy",
    imageUrl: "/blue-white-rope-toy.png",
    sku: 'H123THPQ',
  },
  {
    uuid: "8",
    name: "Paw Print Fleece Blanket",
    description: "Cozy fleece blanket with adorable paw prints. Beige with blue and orange paw print pattern.",
    price: 24.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/placeholder-t7tjp.png",
    sku: 'H123THPW',
  },
  {
    uuid: "9",
    name: "Adjustable Pet Collar",
    description: "Comfortable adjustable collar for daily wear. Durable black material with secure buckle.",
    price: 13.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/black-adjustable-pet-collar.png",
    sku: 'H123THPE',
  },
  {
    uuid: "10",
    name: "Grooming Glove",
    description: "Professional grooming glove for gentle brushing. Blue with black accents and rubber tips.",
    price: 16.99,
    stock: 1,
    category: "grooming",
    imageUrl: "/blue-grooming-glove.png",
    sku: 'H123THPP',
  },
  {
    uuid: "11",
    name: "Nail File",
    description: "Professional nail file for pet grooming. Red and silver design with ergonomic grip.",
    price: 7.99,
    stock: 1,
    category: "grooming",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H123THPL',
  },
  {
    uuid: "12",
    name: "Nail Clipper",
    description: "Precision nail clipper for safe trimming. Black and red design with safety guard.",
    price: 12.99,
    stock: 1,
    category: "grooming",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H123THKP',
  },
  {
    uuid: "13",
    name: "Metal Pet Bowls",
    description: "Stainless steel feeding bowls for food and water. Durable silver finish, set of 2.",
    price: 18.99,
    stock: 2,
    category: "accessory",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H123TUHP',
  },
  {
    uuid: "14",
    name: "Organic Dry Pet Food",
    description: "Premium organic dry food with raw meat as main ingredient. Brown, green, and orange packaging.",
    price: 34.99,
    stock: 5,
    category: "food",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H12T3THP',
  },
  {
    uuid: "15",
    name: "Rope Leash",
    description: "Strong rope leash for walks and training. Black and white braided design with comfortable grip.",
    price: 19.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H123RTHP',
  },
  {
    uuid: "16",
    name: "Treat Pouch",
    description: "Convenient treat pouch for training sessions. Gray exterior with neon green interior.",
    price: 14.99,
    stock: 1,
    category: "accessory",
    imageUrl: "/placeholder.svg?height=300&width=300",
    sku: 'H12V3THP',
  },
]

export const categories = [
  { uuid: "all", name: "All Products" },
  { uuid: "toy", name: "Toys" },
  { uuid: "accessory", name: "Accessories" },
  { uuid: "food", name: "Food" },
  { uuid: "grooming", name: "Grooming" },
]
